= Monitoring and Health Checks

Kubernetes supports monitoring applications in the form of readiness and liveness probes. Health checks can be performed on each container in a Pod. Readiness probes indicate when a Pod is "ready" to serve traffic. Liveness probes indicate a container is "alive". If a liveness probe fails multiple times the container will be restarted. Liveness probes that continue to fail will cause a Pod to enter a crash loop. If a readiness check fails the container will be marked as not ready and will be removed from any load balancers.

Both readiness and liveness probes run on the container during the entire container lifecycle. Kubernetes behaviour based on probes results can be sum up with this table :

|===
|Probe status|Readiness probe|Liveness probe

|✅ Success
|Container is ready: traffic is served
|Container is alive: do nothing

|❌ Failure
|Container is temporarily down: stop serving traffic
|Container crashed: restart it
|===

In this chapter you will deploy a new Pod named `distance-calculator-with-distances`, which is largely based on the `distance-calculator` Pod with the addition of readiness and liveness probes.

In this chapter you will learn how to:

* Create Pods with readiness and liveness probes
* Troubleshoot failing readiness and liveness probes

== Tutorial: Creating Pods with Liveness and Readiness Probes

Explore the `distance-calculator-with-distances` pod configuration file:

```
cat manifests/app/pods/distance-calculator-with-distances.yaml
```

Create the `distance-calculator-with-distances` pod using kubectl:

```
kubectl create -f manifests/app/pods/distance-calculator-with-distances.yaml
```

== Exercise: View Pod details

Pods will not be marked ready until the readiness probe returns an HTTP 200 response. Use the `kubectl describe` to view details for the `distance-calculator-with-distances` Pod.

=== Hints

```
kubectl describe pods <pod-name>
```

=== Quiz

* How is the readiness of the `distance-calculator-with-distances` Pod determined?
* How is the liveness of the `distance-calculator-with-distances` Pod determined?
* How often is the readiness probe checked?
* How often is the liveness probe checked?

> The `distance-calculator-with-distances` Pod logs each health check. Use the `kubectl logs` command to view them.

== Tutorial: Experiment with Readiness Probes

In this tutorial you will observe how Kubernetes responds to failed readiness probes. The `distance-calculator` container supports the ability to force failures of it's readiness and liveness probes. This will enable us to simulate failures for the `distance-calculator-with-distances` Pod.

Use the `kubectl port-forward` command to forward a local port to the health port of the `distance-calculator-with-distances` Pod.

```
kubectl port-forward distance-calculator-with-distances 10081:8082
```

> You now have access to the `/probes/readiness` and `/probes/liveness` HTTP endpoints exposed by the `distance-calculator-with-distances` container.

=== Experiment with Readiness Probes

Force the `distance-calculator-with-distances` container readiness probe to fail. Use the `curl` command to toggle the readiness probe status:

```
curl http://127.0.0.1:10081/probes/readiness/fail
```

Wait about 45 seconds and get the status of the `distance-calculator-with-distances` Pod using the `kubectl get pods` command:

```
watch kubectl get pods distance-calculator-with-distances
```

TIP: `watch` has been added to the command so you don't have to run it the command multiple times

Use the `kubectl describe` command to get more details about the failing readiness probe:

```
kubectl describe pods distance-calculator-with-distances
```

> Notice the events for the `distance-calculator-with-distances` Pod report details about failing readiness probe.

Force the `distance-calculator` container readiness probe to pass. Use the `curl` command to toggle the readiness probe status:

```
curl http://127.0.0.1:10081/probes/readiness/success
```

Wait about 15 seconds and get the status of the `distance-calculator-with-distances` Pod using the `kubectl get pods` command:

```
watch kubectl get pods distance-calculator-with-distances
```

== Exercise: Experiment with Liveness Probes

Building on what you learned in the previous tutorial use the `kubectl port-forward` and `curl` commands to force the `distance-calculator` container liveness probe to fail. Observe how Kubernetes responds to failing liveness probes.

=== Hints

```
kubectl port-forward distance-calculator-with-distances 10081:8082
```

```
curl http://127.0.0.1:10081/probes/liveness/fail
```

=== Quiz

* What happened when the liveness probe failed?
* What events where created when the liveness probe failed?

== Summary

In this chapter you learned that Kubernetes supports application monitoring using
liveness and readiness probes. You also learned how to add readiness and liveness probes to Pods and what happens when probes fail. 
