= Rolling out Updates


Kubernetes makes it easy to rollout updates to your applications using the builtin rolling update mechanism. In this chapter you will learn how to:

* Modify deployments to trigger rolling updates
* Pause and resume an active rolling update
* Rollback a deployment to a previous revision

== Tutorial: Rollout a new version of the Travel Manager service

First look at the current history of the __Deployment__ resource for the `travel-manager` service:
```shell
kubectl rollout history deployment travel-manager
```

Then deploy the travel-manager` deployment` in a newer version (v2) to replace the pod's container image version. With `kubectl apply`, you can live-update a deployment. `--record` option let you keep a trace of the commands related to each deployment change:
```shell
kubectl apply -f manifests/app/deployments/travel-manager-v2.yaml --record
kubectl describe deployments travel-manager
```

If you list __ReplicaSets__, you'll see one for the original version and the other for the new version.
```shell
kubectl get replicasets
```

Now list __Deployment__ history again to see your change history.
```shell
kubectl rollout history deployment travel-manager
```
In fact, __Deployment__ history is backed by the __ReplicaSet__

Just to be sure, make sure you check that the v2 has been correctly deployed:

```shell
curl http://<INGRESS_IP>:60000/version
```

You should now see '0.0.2'.

== Tutorial: Pause and Resume an Active Rollout

Let's try to see a deployment in progress.

First scale the distance-calculator Deployment to 6 pods:
```shell
kubectl scale deployments distance-calculator --replicas=6
```

Look at your __Deployment__ history.
```shell
kubectl rollout history deployment distance-calculator
```

Now modify the distance-calculator deployment image to update `distance-calculator` docker image`s version:
```shell
sed -i 's/distance-calculator:0.0.1/distance-calculator:0.0.2/' manifests/app/deployments/distance-calculator.yaml
```
Now, run following commands all together:
```shell
kubectl apply -f manifests/app/deployments/distance-calculator.yaml --record
kubectl describe deployments distance-calculator
kubectl rollout pause deployment distance-calculator
```

You'll see the __Deployment__ rolling-upgrade stopped in the middle.

Resume the rollout to terminates the rolling-upgrade.

```shell
kubectl rollout resume deployment distance-calculator
```

== Exercise: Rollback the Hello service

Use the `kubectl rollout undo deploy travel-manager` command to rollback to a previous deployment of the Travel Manager service.

After a few seconds check that you are back on version v1:

```shell
curl http://<INGRESS_IP>:60000/version
```

You should now see '0.0.1'.

== Summary

In this chapter you learned how to rollout updates to your applications by modifying deployment objects to trigger rolling updates. You also learned how to pause and resume an active rolling update and rollback it back using the `kubectl rollout` command.