image: node:10

build:
  stage: build
  before_script:
  - node --version
  - npm --version
  - yarn --version
  - yarn
  script:
  - yarn build
  artifacts:
    paths:
    - dist/*
    expire_in: 30 days

pages:
  stage: deploy
  script:
  - mkdir public/
  - cp -r dist/* public/
  - ls -la public/
  artifacts:
      paths:
      - public
  only:
  - master
  - tags