apiVersion: v1
kind: Service
metadata:
  name: liveness-http2
  labels:
    app: liveness-http2
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: liveness-http2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: liveness-http2
spec:
  template:
    metadata:
      labels:
        app: liveness-http2
        version: v1
    spec:
      containers:
      - name: liveness-http2
        image: gcr.io/cloudnativestack-playground/frontend
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 5
        env:
        - name: PRODUCT_URL
          value: http://product
        - name: STOCK_URL
          value: http://stock
        - name: SERVER_PORT
          value: "80"
