apiVersion: v1
kind: Service
metadata:
  name: recommendation
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: recommendation
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: recommendation
    version: v2
  name: recommendation-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
      version: v2
  template:
    metadata:
      labels:
        app: recommendation
        version: v2
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xmx256m
        image: abdennebi/recommendation:v2_slow
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
                path: /health
                port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 10
        name: recommendation
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        readinessProbe:
          httpGet:
                path: /health
                port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 5
          timeoutSeconds: 10
        securityContext:
          privileged: false
