apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: python
  name: python
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: python
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: python
    spec:
      containers:
        - image: eu.gcr.io/tcife2-sandbox-ato/test-server
          imagePullPolicy: Always
          name: python
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: kubernetes-api-account-credentials
              readOnly: true
              mountPath: "/etc/kubernetes-api-account-credentials"
            - name: service-account
              readOnly: true
              mountPath: "/tmp/service-account-credentials"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: kubepingsa
      serviceAccountName: kubepingsa
      volumes:
        - name: kubernetes-api-account-credentials
          secret:
            secretName: kubernetes-api-account-credentials
        - name: service-account
          secret:
            secretName: kubepingsa-token-t7nkr