apiVersion: v1
kind: Service
metadata:
  name: "travel-manager"
spec:
  type: NodePort
  selector:
    app: travel-manager
    version: 1
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31000
