apiVersion: v1
kind: Service
metadata:
  name: "travel-manager"
spec:
  type: LoadBalancer
  selector:
    app: travel-manager
    version: v1
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 8081